import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import Navbar from "@/components/Header";
import Footer from "@/components/footer";
import localFont from 'next/font/local';

const satoshi = localFont({
  src: [
    { path: '../../public/fonts/satoshi/Satoshi-Light.woff2', weight: '300' },
    { path: '../../public/fonts/satoshi/Satoshi-Regular.woff2', weight: '400' },
    { path: '../../public/fonts/satoshi/Satoshi-Medium.woff2', weight: '500' },
    { path: '../../public/fonts/satoshi/Satoshi-Bold.woff2', weight: '700' },
    { path: '../../public/fonts/satoshi/Satoshi-Black.woff2', weight: '900' },
    { path: '../../public/fonts/satoshi/Satoshi-Italic.woff2', weight: '400', style: 'italic' },
    { path: '../../public/fonts/satoshi/Satoshi-BoldItalic.woff2', weight: '700', style: 'italic' },
  ],
  variable: '--font-satoshi',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${satoshi.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-4 right-4 z-50">
            <ThemeToggle />
          </div>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
